[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  # Astro corre en el puerto 4321
  targetPort = 4321
  # Netlify Dev expone todo (sitio + lambdas) en el puerto 8888
  port       = 8888
  functions  = "netlify/functions"

[[forms]]
  name = "cotizacion"

[[forms]]
  name = "contacto"
