backend:
  name: git-gateway
  branch: main # Cambia a "master" si tu rama principal es "master"

media_folder: "public/images/uploads" # Donde se guardarán los archivos subidos
public_folder: "/images/uploads" # URL pública para los archivos subidos

collections:
  # Colección para destinos
  - name: "destinations"
    label: "Destinos"
    folder: "src/content/destinations"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Tipo", name: "type", widget: "select", options: ["nacional", "internacional", "crucero"] }
      - { label: "Región", name: "region", widget: "string" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Moneda", name: "currency", widget: "select", options: ["COP", "USD"], default: "COP" }
      - { label: "Precio en USD", name: "priceInUsd", widget: "boolean", default: false }
      - { label: "Precio Original", name: "originalPrice", widget: "number", required: false }
      - { label: "Duración (días)", name: "duration", widget: "number" }
      - { label: "Texto Duración", name: "durationText", widget: "string" }
      - { label: "Imagen Principal", name: "image", widget: "image" }
      - { label: "Galería de Imágenes", name: "gallery", widget: "list", field: { label: "Imagen", name: "image", widget: "image" }, required: false }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Puntuación", name: "rating", widget: "number", min: 0, max: 100 }
      - { label: "Disponibilidad", name: "availability", widget: "number" }
      - { label: "Etiqueta Principal", name: "tag", widget: "select", options: ["Aniversario", "Aventura", "Cultural", "Ecoturismo", "Familiar", "Ocio", "Oferta", "Playa", "Romántico", "Todo Incluido", "Crucero"] }
      - { label: "Etiquetas Adicionales", name: "tags", widget: "select", options: ["Aniversario", "Aventura", "Cultural", "Ecoturismo", "Familiar", "Ocio", "Oferta", "Playa", "Romántico", "Todo Incluido", "Crucero"], multiple: true, required: false }
      - { label: "Incluye", name: "includes", widget: "list", required: false }
      - { label: "No Incluye", name: "notIncludes", widget: "list", required: false }
      - { label: "Notas", name: "notes", widget: "text", required: false }
      - { label: "Naviera (para cruceros)", name: "cruiseLine", widget: "string", required: false }
      - { label: "Barco (para cruceros)", name: "ship", widget: "string", required: false }
      - { label: "Puertos (para cruceros)", name: "ports", widget: "list", required: false }

  # Colección para rutas populares de cruceros
  - name: "cruise-routes"
    label: "Rutas populares de cruceros"
    folder: "src/content/cruise-routes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre de la ruta", name: "name", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Duración", name: "duration", widget: "string", hint: "Ej: 7-10 días" }
      - { label: "Activo", name: "active", widget: "boolean", default: true }
      - { label: "Orden", name: "order", widget: "number", default: 0 }    

   # Colección para bancos aliados y financieras
  - name: "financing-partners"
    label: "Bancos Aliados"
    folder: "src/content/financing-partners"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string", required: true }
      - { label: "Nombre", name: "name", widget: "string", hint: "Nombre de la entidad financiera" }
      - { label: "Logo", name: "logo", widget: "image", hint: "Logo de la entidad financiera" }
      - { label: "Activo", name: "active", widget: "boolean", default: true, hint: "Mostrar u ocultar este banco" }
      - { label: "Orden", name: "order", widget: "number", default: 0, hint: "Posición de visualización (0 primero)" }


    # Colección para categorías
  - name: "categories"
    label: "Categorías"
    folder: "src/content/categories"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Destinos Populares", name: "destinations", widget: "list" }
      - { label: "Tipo", name: "type", widget: "select", options: ["nacional", "internacional", "crucero"], required: false }
      - { label: "URL", name: "url", widget: "string", hint: "URL completa con barra inicial, ej: /destinos/tag/aventura" }
      - { label: "Etiqueta Principal", name: "tag", widget: "select", options: ["Aniversario", "Aventura", "Cultural", "Ecoturismo", "Familiar", "Ocio", "Oferta", "Playa", "Romántico", "Todo Incluido", "Crucero"] }
      - { label: "Etiquetas Adicionales", name: "tags", widget: "select", options: ["Aniversario", "Aventura", "Cultural", "Ecoturismo", "Familiar", "Ocio", "Oferta", "Playa", "Romántico", "Todo Incluido", "Crucero"], multiple: true, required: false }

  # Colección para alianzas
  - name: "alliances"
    label: "Alianzas Estratégicas"
    folder: "src/content/alliances"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string", hint: "Identificador único para la alianza (sin espacios ni caracteres especiales)" }
      - { label: "Nombre", name: "name", widget: "string", hint: "Nombre corto de la alianza" }
      - { label: "Nombre Completo", name: "fullName", widget: "string", hint: "Nombre completo o legal de la entidad" }
      - { label: "Descripción", name: "description", widget: "text", hint: "Breve descripción de la alianza y sus beneficios principales" }
      - { label: "Logo", name: "logo", widget: "image", hint: "Logo de la entidad aliada (preferiblemente con fondo transparente)" }
      - { label: "Beneficios", name: "benefits", widget: "list", hint: "Lista de beneficios específicos para esta alianza", min: 1 }
      - { label: "Activo", name: "active", widget: "boolean", default: true, hint: "Mostrar u ocultar esta alianza en el sitio" }

  # Colección para diapositivas del Hero
  - name: "hero-slides"
    label: "Diapositivas Hero"
    folder: "src/content/hero-slides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Texto de Oferta", name: "offerText", widget: "string", hint: "Ej: Desde $2,499,000 COP" }
      - { label: "Texto del Botón", name: "buttonText", widget: "string", default: "Ver oferta" }
      - { label: "URL del Botón", name: "buttonUrl", widget: "string", hint: "Ej: /destinos/internacionales/cancun" }
      - { label: "Orden", name: "order", widget: "number", default: 0, hint: "Posición de la diapositiva (0 es la primera)" }
      - { label: "Activo", name: "active", widget: "boolean", default: true }

  # Colección para entradas de blog
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string", required: false }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Equipo AL mundo Tour" }
      - { label: "Categorías", name: "categories", widget: "list", default: ["Viajes"] }
      - { label: "Tags", name: "tags", widget: "list", default: ["viajes"] }
      - { label: "Imagen destacada", name: "featuredImage", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Publicado", name: "published", widget: "boolean", default: true }